GPU Prolog Script v0.30
This is a GPU node.
Enough GPUs available.
Allocating card 1
gonzo-605-15.local
Mon 22 Feb 14:28:07 GMT 2021
2021-02-22 14:28:30.979485: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
WARNING:root:sample_label is not used in predict. It is True if and only if mode == 'train'.
2021-02-22 14:29:01.404568: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcuda.so.1
2021-02-22 14:29:01.418605: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1716] Found device 0 with properties: 
pciBusID: 0000:02:00.0 name: GeForce GTX 1080 Ti computeCapability: 6.1
coreClock: 1.582GHz coreCount: 28 deviceMemorySize: 10.92GiB deviceMemoryBandwidth: 451.17GiB/s
2021-02-22 14:29:01.418650: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
2021-02-22 14:29:01.422377: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcublas.so.10
2021-02-22 14:29:01.424788: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcufft.so.10
2021-02-22 14:29:01.425802: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcurand.so.10
2021-02-22 14:29:01.428783: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcusolver.so.10
2021-02-22 14:29:01.431154: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcusparse.so.10
2021-02-22 14:29:01.437055: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudnn.so.7
2021-02-22 14:29:01.438995: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1858] Adding visible gpu devices: 0
2021-02-22 14:29:01.453795: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN)to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2021-02-22 14:29:01.479281: I tensorflow/core/platform/profile_utils/cpu_utils.cc:104] CPU Frequency: 2400025000 Hz
2021-02-22 14:29:01.481202: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x5576db0 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2021-02-22 14:29:01.481230: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2021-02-22 14:29:01.488809: W tensorflow/compiler/xla/service/platform_util.cc:210] unable to create StreamExecutor for CUDA:0: failed initializing StreamExecutor for CUDA device ordinal 0: Internal: failed call to cuDevicePrimaryCtxRetain: CUDA_ERROR_INVALID_DEVICE: invalid device ordinal
2021-02-22 14:29:01.488907: I tensorflow/compiler/jit/xla_gpu_device.cc:161] Ignoring visible XLA_GPU_JIT device. Device number is 0, reason: Internal: no supported devices found for platform CUDA
2021-02-22 14:29:01.489645: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1716] Found device 0 with properties: 
pciBusID: 0000:02:00.0 name: GeForce GTX 1080 Ti computeCapability: 6.1
coreClock: 1.582GHz coreCount: 28 deviceMemorySize: 10.92GiB deviceMemoryBandwidth: 451.17GiB/s
2021-02-22 14:29:01.489683: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
2021-02-22 14:29:01.489713: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcublas.so.10
2021-02-22 14:29:01.489728: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcufft.so.10
2021-02-22 14:29:01.489755: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcurand.so.10
2021-02-22 14:29:01.489770: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcusolver.so.10
2021-02-22 14:29:01.489787: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcusparse.so.10
2021-02-22 14:29:01.489803: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudnn.so.7
2021-02-22 14:29:01.490725: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1858] Adding visible gpu devices: 0
2021-02-22 14:29:01.490753: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
Traceback (most recent call last):
  File "/home/bryanko/venvs/deepreg/lib/python3.7/site-packages/tensorflow/python/data/util/structure.py", line 93, in normalize_element
    spec = type_spec_from_value(t, use_fallback=False)
  File "/home/bryanko/venvs/deepreg/lib/python3.7/site-packages/tensorflow/python/data/util/structure.py", line 466, in type_spec_from_value
    (element, type(element).__name__))
TypeError: Could not build a TypeSpec for 0 with type int

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bryanko/venvs/deepreg/bin/deepreg_predict", line 33, in <module>
    sys.exit(load_entry_point('deepreg', 'console_scripts', 'deepreg_predict')())
  File "/home/bryanko/DeepReg/deepreg/predict.py", line 435, in main
    save_png=args.png,
  File "/home/bryanko/DeepReg/deepreg/predict.py", line 299, in predict
    repeat=False,
  File "/home/bryanko/DeepReg/deepreg/util.py", line 44, in build_dataset
    training=training, repeat=repeat, **preprocess_config
  File "/home/bryanko/DeepReg/deepreg/dataset/loader/interface.py", line 100, in get_dataset_and_preprocess
    dataset = self.get_dataset()
  File "/home/bryanko/DeepReg/deepreg/dataset/loader/interface.py", line 269, in get_dataset
    indices=self.num_indices,
  File "/home/bryanko/venvs/deepreg/lib/python3.7/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 910, in from_generator
    id_dataset = Dataset.from_tensors(dummy)
  File "/home/bryanko/venvs/deepreg/lib/python3.7/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 604, in from_tensors
    return TensorDataset(tensors)
  File "/home/bryanko/venvs/deepreg/lib/python3.7/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 2982, in __init__
    element = structure.normalize_element(element)
  File "/home/bryanko/venvs/deepreg/lib/python3.7/site-packages/tensorflow/python/data/util/structure.py", line 98, in normalize_element
    ops.convert_to_tensor(t, name="component_%d" % i))
  File "/home/bryanko/venvs/deepreg/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 1499, in convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/home/bryanko/venvs/deepreg/lib/python3.7/site-packages/tensorflow/python/framework/tensor_conversion_registry.py", line 52, in _default_conversion_function
    return constant_op.constant(value, dtype, name=name)
  File "/home/bryanko/venvs/deepreg/lib/python3.7/site-packages/tensorflow/python/framework/constant_op.py", line 264, in constant
    allow_broadcast=True)
  File "/home/bryanko/venvs/deepreg/lib/python3.7/site-packages/tensorflow/python/framework/constant_op.py", line 275, in _constant_impl
    return _constant_eager_impl(ctx, value, dtype, shape, verify_shape)
  File "/home/bryanko/venvs/deepreg/lib/python3.7/site-packages/tensorflow/python/framework/constant_op.py", line 300, in _constant_eager_impl
    t = convert_to_eager_tensor(value, ctx, dtype)
  File "/home/bryanko/venvs/deepreg/lib/python3.7/site-packages/tensorflow/python/framework/constant_op.py", line 97, in convert_to_eager_tensor
    ctx.ensure_initialized()
  File "/home/bryanko/venvs/deepreg/lib/python3.7/site-packages/tensorflow/python/eager/context.py", line 539, in ensure_initialized
    context_handle = pywrap_tfe.TFE_NewContext(opts)
tensorflow.python.framework.errors_impl.InternalError: CUDA runtime implicit initialization on GPU:0 failed. Status: all CUDA-capable devices are busy or unavailable
Mon 22 Feb 14:29:05 GMT 2021
GPU Epilog Script v0.30
